# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72483f71f81bd259612de98fa6d54e50a01d8ccdbe4e66cec1086e55b2b02c57a8805216ed0f15761659b0c91a0d85b088e1c52c10dc2d23f695f26f7ebcb51a

test:
  secret_key_base: afd0954e8d63716af710165a6d57e1c2f9c0a047dc728fd198ffe49d7d28f7797d45c9a7f31b9e31947d812bd6c075c9b1998757d748d65a96e9a98fba3dcf65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
